version: 1.0.1000000.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: VyyiHIJv/p8KuVZ+2RWsU/NqCHxNM7hcLupLOzhtKf0gRygNzr7ZInC28MQjs/fA
  CODECOV_REPO_TOKEN:
    secure: ZA1rwa+G7T3mqc7f9WqDN96OAra/FtINQth4q71rXu3s3+gWJnH3us+zhduL2MbO
install:
- cmd: git submodule update --init --recursive
- ps: >-
    dotnet --info
build_script:
- ps: .\build.ps1 -Target Appveyor
artifacts:
- path: .\artifacts\*.nupkg
- path: .\coverage-results\*
test: off
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
